mhsb/urls.py
from django.urls import path
from mhsb import views
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('mhsb/weapon/', views.WeaponView.as_view(), name='weapon'),
    path('mhsb/sousyoku/', views.SousyokuView.as_view(), name='sousyoku'),
    path('mhsb/kyouka/', views.KyoukaView.as_view(), name='kyouka'),
    path('mhsb/form_1/', views.FormCreate_1, name='form_1'),
    path('mhsb/form_2/', views.FormCreate_2, name='form_2'),
    path('mhsb/form_3/', views.FormCreate_3, name='form_3'),
    path('mhsb/form_4/', views.FormCreate_4, name='form_4'),
    path('mhsb/post_detail_1/<int:pk>/', views.PostDetailView_1.as_view(), name='post_detail_1'),
    path('mhsb/post_detail_2/<int:pk>/', views.PostDetailView_2.as_view(), name='post_detail_2'),
    path('mhsb/post_detail_3/<int:pk>/', views.PostDetailView_3.as_view(), name='post_detail_3'),
    path('mhsb/post_detail_4/<int:pk>/', views.PostDetailView_4.as_view(), name='post_detail_4'),
    path('mhsb/comment_1/<int:post_pk>/', views.CommentCreate_1, name='commentcreate_1'),
    path('mhsb/comment_2/<int:post_pk>/', views.CommentCreate_2, name='commentcreate_2'),
    path('mhsb/comment_3/<int:post_pk>/', views.CommentCreate_3, name='commentcreate_3'),
    path('mhsb/comment_4/<int:post_pk>/', views.CommentCreate_4, name='commentcreate_4'),
    path('mhsb/formlist_1/', views.FormListView_1, name='formlist_1'),
    path('mhsb/formlist_2/', views.FormListView_2, name='formlist_2'),
    path('mhsb/formlist_3/', views.FormListView_3, name='formlist_3'),
    path('mhsb/formlist_4/', views.FormListView_4, name='formlist_4'), 
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mhsb.urls')), 
    
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mhsb/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Post_1(models.Model):
    user = models.CharField(max_length=30, default='名無しのハンター')
    content = models.TextField('本文', null=False, max_length=1000)
    created = models.DateTimeField('作成日', default=timezone.now)
    picture = models.ImageField(upload_to = 'images', verbose_name='画像', blank=True)
    
    class Meta:
        pass
    
    def __str__(self):
        return self.user
    
class Comment_1(models.Model):
    user = models.CharField('名前', max_length=30, default='名無しのハンター')
    message = models.TextField('本文', null=False, max_length=1000)
    target = models.ForeignKey(Post_1, on_delete=models.CASCADE, verbose_name='対象記事')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    class Meta:
        ordering = ('-created_at',) 
    
    def __str__(self):
        return self.message[:20]    
    
    
    
class Post_2(models.Model):
    user = models.CharField(max_length=30, default='名無しのハンター')
    content = models.TextField('本文', null=False, max_length=1000)
    created = models.DateTimeField('作成日', default=timezone.now)
    picture = models.ImageField(upload_to = 'images', verbose_name='画像', blank=True)
    
    class Meta:
        pass
    
    def __str__(self):
        return self.user
    
class Comment_2(models.Model):
    user = models.CharField('名前', max_length=30, default='名無しのハンター')
    message = models.TextField('本文', null=False, max_length=1000)
    target = models.ForeignKey(Post_2, on_delete=models.CASCADE, verbose_name='対象記事')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    class Meta:
        ordering = ('-created_at',) 

    def __str__(self):
        return self.message[:20]    
    
class Post_3(models.Model):
    user = models.CharField(max_length=30, default='名無しのハンター')
    content = models.TextField('本文', null=False, max_length=1000)
    created = models.DateTimeField('作成日', default=timezone.now)
    picture = models.ImageField(upload_to = 'images', verbose_name='画像', blank=True)
    
    class Meta:
        pass
    
    def __str__(self):
        return self.user
    
class Comment_3(models.Model):
    user = models.CharField('名前', max_length=30, default='名無しのハンター')
    message = models.TextField('本文', null=False, max_length=1000)
    target = models.ForeignKey(Post_3, on_delete=models.CASCADE, verbose_name='対象記事')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    class Meta:
        ordering = ('-created_at',) 
    
    def __str__(self):
        return self.message[:20]    
    
class Post_4(models.Model):
    user = models.CharField(max_length=30, default='名無しのハンター')
    content = models.TextField('本文', null=False, max_length=1000)
    created = models.DateTimeField('作成日', default=timezone.now)
    picture = models.ImageField(upload_to = 'images', verbose_name='画像', blank=True)
    
    class Meta:
        pass
    
    def __str__(self):
        return self.user
    
class Comment_4(models.Model):
    user = models.CharField('名前', max_length=30, default='名無しのハンター')
    message = models.TextField('本文', null=False, max_length=1000)
    target = models.ForeignKey(Post_4, on_delete=models.CASCADE, verbose_name='対象記事')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    class Meta:
        ordering = ('-created_at',) 
    
    def __str__(self):
        return self.message[:20]    

mhsb/forms.py
from django import forms
from .models import Post_1,Post_2,Post_3,Post_4,Comment_1,Comment_2,Comment_3,Comment_4

class PostForm_1(forms.ModelForm):
   class Meta:
       model = Post_1
       exclude = ('created',)
       
class CommentForm_1(forms.ModelForm):
    class Meta:
        model = Comment_1
        exclude = ('target', 'created_at')
       
class PostForm_2(forms.ModelForm):
   class Meta:
       model = Post_2
       exclude = ('created',)

class CommentForm_2(forms.ModelForm):
    class Meta:
        model = Comment_2
        exclude = ('target', 'created_at')
       
class PostForm_3(forms.ModelForm):
   class Meta:
       model = Post_3
       exclude = ('created',)

class CommentForm_3(forms.ModelForm):
    class Meta:
        model = Comment_3
        exclude = ('target', 'created_at')
       
class PostForm_4(forms.ModelForm):
   class Meta:
       model = Post_4
       exclude = ('created',)
       
class CommentForm_4(forms.ModelForm):
    class Meta:
        model = Comment_4
        exclude = ('target', 'created_at')
       

mhsb/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import View,DetailView
from django.urls import reverse_lazy, reverse
from .models import Post_1,Post_2,Post_3,Post_4,Comment_1,Comment_2,Comment_3,Comment_4
from .forms import PostForm_1,PostForm_2,PostForm_3,PostForm_4,CommentForm_1,CommentForm_2,CommentForm_3,CommentForm_4
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages

class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'mhsb/index.html')
    
class WeaponView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'mhsb/weapon.html')
    
class SousyokuView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'mhsb/sousyoku.html') 
    
class KyoukaView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'mhsb/kyouka.html') 
    
    
    
    
    
    
#formlist_1
                    
def FormListView_1(request):
    """フォーム画面、ページオブジェクト、投稿内容を渡す"""
    post = Post_1.objects.order_by('-created')
    page_obj = paginate_queryset(request, post, 20)
    form = PostForm_1
    context = {
        'form': form,
        'page_obj': page_obj,
        'post_list' : page_obj.object_list,
    }

    return render(request, 'mhsb/formlist_1.html', context)
    
def paginate_queryset(request, queryset, count):
    """ページネーションをするためのメソッド"""
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj

def FormCreate_1(request):
    """フォーム投稿時の処理"""
    form = PostForm_1(request.POST,request.FILES)
    ctx = {"form": form}
    if request.POST:
        if form.is_valid():
            post_list = form.cleaned_data
            obj = Post_1(**post_list)
            obj.save()
            messages.success(request, '投稿しました')
            return redirect("formlist_1")
        
        else:    
            messages.error(request, '投稿できませんでした')
            return render(request, 'mhsb/formlist_1.html', ctx)
 
    
    
    
    
    
#post_detail_1    
    
class PostDetailView_1(DetailView):
    model = Post_1
    form_class = CommentForm_1
    template_name = 'mhsb/post_detail_1.html'
    
    def get_context_data(self, **kwargs):
        """投稿詳細、コメント、フォーム画面を渡す"""
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post_1, pk=self.kwargs['pk'])
        context['comment'] = Comment_1.objects.order_by('-created_at')
        context['comment_form'] = CommentForm_1
        return context
    
def CommentCreate_1(request,post_pk):
    """フォーム投稿時の処理"""
    post = get_object_or_404(Post_1, pk=post_pk)
    form = CommentForm_1(request.POST or None)
    
    if request.method == 'POST':
        comment = form.save(commit=False)
        comment.target = post
        comment.save()
        messages.success(request, 'コメントしました')
        return redirect('post_detail_1', pk=post.pk)

    return render(request,'mhsb/post_detail_1')
 
 
 
 
 
      
      
#formlist_2
    
def FormListView_2(request):
    """フォーム画面、ページオブジェクト、投稿内容を渡す"""
    post = Post_2.objects.order_by('-created')
    page_obj = paginate_queryset(request, post, 20)
    form = PostForm_2
    context = {
        'form': form,
        'page_obj': page_obj,
        'post_list' : page_obj.object_list,
    }

    return render(request, 'mhsb/formlist_2.html', context) 
    
def paginate_queryset(request, queryset, count):
    """ページネーションをするためのメソッド"""
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj

def FormCreate_2(request):
    """フォーム投稿時の処理"""
    form = PostForm_2(request.POST,request.FILES)
    ctx = {"form": form}
    if request.POST:
        if form.is_valid():
            post_list = form.cleaned_data
            obj = Post_2(**post_list)
            obj.save()
            messages.success(request, '投稿しました')
            return redirect("formlist_2")
        
        else:
            messages.error(request, '投稿できませんでした')    
            return render(request, 'mhsb/formlist_2.html', ctx)
 
    
    
    
    
#post_detail_2    
    
class PostDetailView_2(DetailView):
    model = Post_2
    form_class = CommentForm_2
    template_name = 'mhsb/post_detail_2.html'
    
    def get_context_data(self, **kwargs):
        """投稿詳細、コメント、フォーム画面を渡す"""
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post_2, pk=self.kwargs['pk'])
        context['comment'] = Comment_2.objects.order_by('-created_at')
        context['comment_form'] = CommentForm_2
        return context
    
def CommentCreate_2(request,post_pk):
    """フォーム投稿時の処理"""
    post = get_object_or_404(Post_2, pk=post_pk)
    form = CommentForm_2(request.POST or None)
    
    if request.method == 'POST':
        comment = form.save(commit=False)
        comment.target = post
        comment.save()
        messages.success(request, 'コメントしました')
        return redirect('post_detail_2', pk=post.pk)
    
    return render(request,'mhsb/post_detail_2')
      
      
      
      
      
      
      
      
      
#formlist_3

def FormListView_3(request):
    """フォーム画面、ページオブジェクト、投稿内容を渡す"""
    post = Post_3.objects.order_by('-created')
    page_obj = paginate_queryset(request, post, 20)
    form = PostForm_3
    context = {
        'form': form,
        'page_obj': page_obj,
        'post_list' : page_obj.object_list,
    }

    return render(request, 'mhsb/formlist_3.html', context) 
    
    
def paginate_queryset(request, queryset, count):
    """ページネーションをするためのメソッド"""
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj


def FormCreate_3(request):
    """フォーム投稿時の処理"""
    form = PostForm_3(request.POST,request.FILES)
    ctx = {"form": form}
    if request.POST:
        if form.is_valid():
            post_list = form.cleaned_data
            obj = Post_3(**post_list)
            obj.save()
            messages.success(request, '投稿しました')
            return redirect("formlist_3")
        
        else:
            messages.error(request, '投稿できませんでした')
            return render(request, 'mhsb/formlist_3.html', ctx)
 
    
    
    
    
#post_detail_3    
    
class PostDetailView_3(DetailView):
    model = Post_3
    form_class = CommentForm_3
    template_name = 'mhsb/post_detail_3.html'
    
    def get_context_data(self, **kwargs):
        """投稿詳細、コメント、フォーム画面を渡す"""
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post_3, pk=self.kwargs['pk'])
        context['comment'] = Comment_3.objects.order_by('-created_at')
        context['comment_form'] = CommentForm_3
        return context
    
def CommentCreate_3(request,post_pk):
    """フォーム投稿時の処理"""
    post = get_object_or_404(Post_3, pk=post_pk)
    form = CommentForm_3(request.POST or None)
    
    if request.method == 'POST':
        comment = form.save(commit=False)
        comment.target = post
        comment.save()
        messages.success(request, 'コメントしました')
        return redirect('post_detail_3', pk=post.pk)

    return render(request,'mhsb/post_detail_3')
    
    
    
    
    
    
    
                
#formlist_4        

def FormListView_4(request):
    """フォーム画面、ページオブジェクト、投稿内容を渡す"""
    post = Post_4.objects.order_by('-created')
    page_obj = paginate_queryset(request, post, 20)
    form = PostForm_4
    context = {
        'form': form,
        'page_obj': page_obj,
        'post_list' : page_obj.object_list,
    }

    return render(request, 'mhsb/formlist_4.html', context) 
    
    
def paginate_queryset(request, queryset, count):
    """ページネーションをするためのメソッド"""
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj


def FormCreate_4(request):
    """フォーム投稿時の処理"""
    form = PostForm_4(request.POST,request.FILES)
    ctx = {"form": form}
    if request.POST:
        if form.is_valid():
            post_list = form.cleaned_data
            obj = Post_4(**post_list)
            obj.save()
            messages.success(request, '投稿しました')
            return redirect("formlist_4")
        else:
            messages.error(request, '投稿できませんでした')
            return render(request, 'mhsb/formlist_4.html', ctx)
 
    
#post_detail_4    
    
class PostDetailView_4(DetailView):
    model = Post_4
    form_class = CommentForm_4
    template_name = 'mhsb/post_detail_4.html'
    
    def get_context_data(self, **kwargs):
        """投稿詳細、コメント、フォーム画面を渡す"""
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post_4, pk=self.kwargs['pk'])
        context['comment'] = Comment_4.objects.order_by('-created_at')
        context['comment_form'] = CommentForm_4
        return context  
    
def CommentCreate_4(request,post_pk):
    """フォーム投稿時の処理"""
    post = get_object_or_404(Post_4, pk=post_pk)
    form = CommentForm_4(request.POST or None)
    
    if request.method == 'POST':
        comment = form.save(commit=False)
        comment.target = post
        comment.save()
        messages.success(request, 'コメントしました')

mhsb/templates/mhsb/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>MHSB ～傀異探究～</title>
</head>
<body>
<header class='site-header'>
    <img src="{% static "mhsb_images/header_img.jpg" %}" alt="header_img" class='header_img'>
    <div class='header-main'>
        <h1 class='logo'>MHSB ～傀異探究～</h1>
    </div> 
    <div class='header-sub'>     
        <div class="gnavi__wrap">
            <ul class="gnavi__lists"> 
                <li class="gnavi__list"><a href='/'>傀異モンスター一覧</a></li>
                <li class="gnavi__list"><a href="{% url 'weapon' %}">武  器</a></li>
                <li class="gnavi__list"><a href="{% url 'sousyoku' %}">装飾品</a></li>
                <li class="gnavi__list"><a href="{% url 'kyouka' %}">武器傀異強化</a></li>
                <li class="gnavi__list">
                    <a href="{% url 'formlist_1' %}">掲示板</a>
                    <ul class="dropdown__lists">
                        <li class="dropdown__list"><a href="{% url 'formlist_1' %}">神おま報告</a></li>
                        <li class="dropdown__list"><a href="{% url 'formlist_2' %}">傀異錬成報告</a></li>
                        <li class="dropdown__list"><a href="{% url 'formlist_3' %}">狩友募集</a></li>
                        <li class="dropdown__list"><a href="{% url 'formlist_4' %}">雑  談</a></li>
                    </ul>
                </li>      
            </ul>       
        </div>
    </div>
    <div class="hamburger-menu">
        <input type="checkbox" id="menu-btn-check">
        <label for="menu-btn-check" class="menu-btn"><span></span></label>
        <div class="menu-content">
            <ul class="menu-list">
                <li>
                    <a href="/">傀異モンスター一覧</a>
                </li>
                <li>
                    <a href="{% url 'weapon' %}">武  器</a>
                </li>
                <li>
                    <a href="{% url 'sousyoku' %}">装飾品</a>
                </li>
                <li>
                    <a href="{% url 'kyouka' %}">武器傀異強化</a>
                </li>
                <li>
                    <a href="{% url 'formlist_1' %}">掲示板</a>        
                </li>
            </ul>
            <ul class = 'menu-list-list'>
                <li><a href="{% url 'formlist_1' %}">・神おま報告</a></li>
                <li><a href="{% url 'formlist_2' %}">・傀異錬成報告</a></li>
                <li><a href="{% url 'formlist_3' %}">・狩友募集</a></li>
                <li><a href="{% url 'formlist_4' %}">・雑  談</a></li>
            </ul>
        </div>
    </div>
    
</header>    
    
      
{% block content %}
{% endblock %}
        
   

<footer>
        
</footer>    
    
</body>
</html>

mhsb/templates/mhsb/post_detail_1.html
{% extends 'mhsb/form_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<h1 class='toukou'>神おま報告</h1>
<h2 class='syosai'>投稿詳細</h2>
    <div class ='deteil_position'>    
        <section class="mt-5">
            <div class="card">
                <div class="card-body">
                    {% if post.picture %}
                        <img src="{{ post.picture.url }}" alt="" width='50%'>
                    {% endif %}   
                        <div class="card-text">
                            <span class="fs-6">{{ post.created }}</span>
                                <p class="fs-6">{{ post.user }}</p>
                            <div class="mt-5">
                                {{ post.content }}
                            </div>
                        </div>
                </div>
            </div>
            <br>
            <br>
            <br>
        <form action="{% url 'commentcreate_1' post.pk %}"  method="POST" id="comment-form">
            {% csrf_token %}
        <!--特定のフィールドに紐づかないエラーを表示する-->
            {{ form.non_field_errors }}
            <!--フォームの各フィールドを取り出す-->
            {% for field in comment_form %}
                <div class="field">
                    {{ field.label_tag }}
                    {% render_field field class="form-control" %}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <br>
            <button class="btn btn-warning" type="submit">コメントする</button>    
        </form>
        <br>
        {% if messages %}
                <div class="container" style="padding:0;">
                    <div class="message">
                    {% for message in messages %}
                        {% if message.tags == "success" %}
                            <div class="alert alert-success" role="alert">
                        {% elif message.tags == "error" %}
                            <div class="alert alert-danger" role="alert">
                        {% else %}
                            <div class="alert alert-info" role="alert">
                        {% endif %}
                            {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                            </div>
            {% endfor %}
                    </div>
                </div>
            {% endif %}
    

        <h3 class="comment-title">コメント</h3>
            <!--コメント-->
            {% for comment in post_1.comment_1_set.all %}
            <div class="comment-list">
                <div class='border-bottom'>{{ comment.user }} {{ comment.created_at }}</div>
                <!--改行しないようlinebreaksを設定,URL要素に<a>要素を設定-->
                <div class='mt-2'>{{ comment.message | linebreaks | urlize }}</div>
            </div>
            {% empty %}
            <p>コメントはありません</p>
            {% endfor %}
            <br>
            <button class="btn btn-primary" onclick="location.href='{% url 'formlist_1' %}'">投稿一覧に戻る</button>      
        </section>
    </div>
{% endblock %}

mhsb/templates/mhsb/post_detail_2.html
{% extends 'mhsb/form_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<h1 class='toukou'>傀異錬成報告</h1>
    <div class ='deteil_position'>    
        <section class="mt-5">
            <div class="card">
                <div class="card-body">
                    {% if post.picture %}
                        <img src="{{ post.picture.url }}" alt="" width='50%'>
                    {% endif %}   
                        <div class="card-text">
                            <span class="fs-6">{{ post.created }}</span>
                                <p class="fs-6">{{ post.user }}</p>
                            <div class="mt-5">
                                {{ post.content }}
                            </div>
                        </div>
                </div>
            </div>
            <br>
            <br>
            <br>
        <form action="{% url 'commentcreate_2' post.pk %}"  method="POST" id="comment-form">
            {% csrf_token %}
        <!--特定のフィールドに紐づかないエラーを表示する-->
            {{ form.non_field_errors }}
            <!--フォームの各フィールドを取り出す-->
            {% for field in comment_form %}
                <div class="field">
                    {{ field.label_tag }}
                    {% render_field field class="form-control" %}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <br>
            <button class="btn btn-warning" type="submit">コメントする</button>    
        </form>
        <br>
        {% if messages %}
            <div class="container" style="padding:0;">
                <div class="message">
                    {% for message in messages %}
                        {% if message.tags == "success" %}
                            <div class="alert alert-success" role="alert">
                        {% elif message.tags == "error" %}
                            <div class="alert alert-danger" role="alert">
                        {% else %}
                            <div class="alert alert-info" role="alert">
                        {% endif %}
                            {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                            </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <h3 class="comment-title">コメント</h3>
            <!--コメント-->
            {% for comment in post_2.comment_2_set.all %}
            <div class="comment-list">
                <div class='border-bottom'>{{ comment.user }} {{ comment.created_at }}</div>
                <!--改行しないようlinebreaksを設定,URL要素に<a>要素を設定-->
                <div class='mt-2'>{{ comment.message | linebreaks | urlize }}</div>
            </div>
            {% empty %}
            <p>コメントはありません</p>
            {% endfor %}
            <br>
            <button class="btn btn-primary" onclick="location.href='{% url 'formlist_2' %}'">投稿一覧に戻る</button>   
        </section>
    </div>
{% endblock %}

mhsb/templates/mhsb/post_detail_3.html
{% extends 'mhsb/form_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<h1 class='toukou'>狩友募集</h1>
    <div class ='deteil_position'>    
        <section class="mt-5">
            <div class="card">
                <div class="card-body">
                    {% if post.picture %}
                        <img src="{{ post.picture.url }}" alt="" width='50%'>
                    {% endif %}   
                        <div class="card-text">
                            <span class="fs-6">{{ post.created }}</span>
                                <p class="fs-6">{{ post.user }}</p>
                            <div class="mt-5">
                                {{ post.content }}
                            </div>
                        </div>
                </div>
            </div>
            <br>
            <br>
            <br>
        <form action="{% url 'commentcreate_3' post.pk %}"  method="POST" id="comment-form">
            {% csrf_token %}
        <!--特定のフィールドに紐づかないエラーを表示する-->
            {{ form.non_field_errors }}
            <!--フォームの各フィールドを取り出す-->
            {% for field in comment_form %}
                <div class="field">
                    {{ field.label_tag }}
                    {% render_field field class="form-control" %}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <br>
            <button class="btn btn-warning" type="submit">コメントする</button>    
        </form>
        <br>
        {% if messages %}
            <div class="container" style="padding:0;">
                <div class="message">
                    {% for message in messages %}
                        {% if message.tags == "success" %}
                            <div class="alert alert-success" role="alert">
                        {% elif message.tags == "error" %}
                            <div class="alert alert-danger" role="alert">
                        {% else %}
                            <div class="alert alert-info" role="alert">
                        {% endif %}
                            {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <h3 class="comment-title">コメント</h3>
            <!--コメント-->
            {% for comment in post_3.comment_3_set.all %}
            <div class="comment-list">
                <div class='border-bottom'>{{ comment.user }} {{ comment.created_at }}</div>
                <!--改行しないようlinebreaksを設定,URL要素に<a>要素を設定-->
                <div class='mt-2'>{{ comment.message | linebreaks | urlize }}</div>
            </div>
            {% empty %}
            <p>コメントはありません</p>
            {% endfor %}
            <br>
            <button class="btn btn-primary" onclick="location.href='{% url 'formlist_3' %}'">投稿一覧に戻る</button>    
        </section>
    </div>
{% endblock %}